# Project Name
TARGET = SG-2

USE_DAISYSP_LGPL = 1

# Sources
CPP_SOURCES = SG-2.cpp

# Library Locations
LIBDAISY_DIR = ../../../../Developer/Daisy/libDaisy
DAISYSP_DIR = ../../../../Developer/Daisy/DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
